### ISSUE TITLE
merge segment handling functions

### ISSUE THREAD

**Issue by ahnitz** [ligo-cbc/pycbc#127]
Ok, Ian, here is the todo list. Please let me know if there is something else I am missing.

#### Task List 
- [x] move science segments to workflow-science
- [x] move veto creation to workflow-vetoes
- [x] add min-segment-length back to science time generation
- [x] make veto function return segment files, and the relevant segment names (still multiple segment files)
- [x] update exes to take SEGMENT_NAME on the command line (for the ones that don't)
  - [x] pycbc_coinc_findtrigs
  - [x] pycbc_plot_params_vs_singles
  - [x] pycbc_page_snrchi
  - [x] pycbc_page_coinc_snrchi
  - [ ] Any others ?????
- [ ] make veto function return single file with all the cumulative lists
- [x] update and test pycbc_make_hdf_coinc_workflow for this model + downstream setup functions
- [ ] update and test pycb_make_coinc_workflow for this model + downstream setup functions 
- [ ] add new option for pregenerated science time
- [ ] add new option for pregenerated veto files 
- [ ] update documentation and example ini files

**Comment by duncan-brown** [comment]
In discussion with Ian, we decided that this is not critical for O1, but should be fixed.

**Comment by spxiwh** [comment]
Hi Alex,

I'm starting to look into this now. I think the first thing I want to do is look at updating the SegFile class.

Cheers
Ian

**Comment by spxiwh** [comment]
Alex, I've just pushed a commit to a devel branch here:

https://github.com/spxiwh/pycbc/commit/62333f3ae6134656f74319a5e1cd2392899a1988

This edits the SegFile class to be able to hold multiple segment lists and provides class methods to replace the functions that were in the event module (I don't think those functions belong in the event module!)

At the moment this won't work with anything, I deliberately changed the class name, but I wanted to check first with you that you agreed with this approach for handling files holding segment lists in the workflow. Currently all segment lists in the file are exposed to the SegFile class, but maybe some convenience functions will be needed to access it easier. With this I could address the first bullet point in the to-do list:

make veto function return single file with all the cumulative lists

**Comment by ahnitz** [comment]
Ian,

I've taken a look at this class, and I think this looks good. I am unsure
about requiring the 'valid seg' argument though, is this really needed in
all cases, especially since it is meant to hold a segment list (or set of)
itself? I think it would be a good replacement for the functions you've
deleted, if this is an optional argument.

-Alex

**Comment by spxiwh** [comment]
Hi Alex,

Thanks, I have updated the code here (still untested, but you can see the idea):

https://github.com/ligo-cbc/pycbc/compare/master...spxiwh:segment_work

The valid_seg and ifo_list options *are* required in the __init__ function because this File *can* be initiated and a segmentlistdict added later. These are a little separate from the segmentfile as the ifo_list and valid_seg sent to the parent File class are the segment and ifos over which the segmentlist is *valid* (kinda like the segment_summary), rather than the extent.

However, I can see that from the classmethods you might just want to ignore this, so I made these kwargs in the class methods. If *not* provided then the extent_all() of the segmentlistdict, and all present ifos will be used in the valid_seg and ifo_list sent to the File class. I would ask though that we *try* to supply these when possible.

**Comment by ahnitz** [comment]
Ok, I'm happy with this now.

**Comment by spxiwh** [comment]
Hey Alex,

While #408 is on hold, I want to continue on this to-do list. So the next item is:

"make veto function return single file with all the cumulative lists"

what exactly are you thinking of here. Certainly if all these segment lists are generated at runtime we can cat all the segment lists together and write a new combined SegFile. Is that what you had in mind?

However, there's really no reason why calls in get_cumulative_veto_group_files should be made at run-time, is there? Ie. I should be able to set execute_now=False here. In that case it is not so easy to cat these files together unless we write an executable to take a list of segment files and cat them together.

What are your thoughts on this? Should we:

a) Go the route of making a cat_segment_lists executable which can then use the execute_now keyword argument in the workflow planner.
b) Use the SegFile class to internally (to the workflow module) construct a concatenated segment file, which will mean that execute_now always has to be True.
c) Continue to have the function get_cumulative_veto_group_files return multiple files.

Are we also happy with how get_analyzable_segments works, or do you want to have it just return SegFile(s)?

**Comment by ahnitz** [comment]
I don't think this list accurately reflects the current status, although more work is needed. Re-open with a more up to description if needed.
