### ISSUE TITLE
hdf results page task list

### ISSUE THREAD

**Issue by ahnitz** [ligo-cbc/pycbc#55]
The hdf based coinc result pages are severely lacking at the moment. Let's come together and count the ways (and hopefully fix some of them too!). Please comment with what should be added to this list, if you are working on some new plot, or are interested in helping out. 

 - [ ] check for missing titles, axis, captions
 - [x] include minifollowups
 - [x] include range plots 
 - [x] meta information is missing (Ian?)
 - [x] ifar plots
 - [ ] tables of loudest background 
 - [ ] tables of loudest missed injections 
 - [ ] use UTC time in addition to GPS wherever it is used
 - [ ] cross links to alog and detchar summary pages
 - [ ] omega scans????
 - [x] site map
 - [x] single detector histograms
More tasks to add to list:
 - [ ] Units on all plots
 - [x] segment and veto information plots
 - [ ] Use green for L1 and red for H1 on all plots
 - [x] Add a overflow bin for extreme outliers on histograms
 - [x] Fix x-axis limit on histograms
 - [x] Change "without little dogs" label in legend to "closed-box background"; explain in caption
 - [ ] Define injected decisive distance in caption
 - [ ] Show linear and log scale for found/missed plot
 - [x] is there any template bank information we can show on the summary page?
 - [ ] Show summary page at a commissioner meeting/telecon
 - [ ] Caption explanation that walks a LSC user with only knowledge of Sensemon range through how it relates to the sensitive distance plots
 - [ ] Add 1.4-1.4 line to sensitive distance plot on summary page
 - [ ] Figure out the scaling factor between L1 and H1 for how SNRs are relative, since they are not collocated
 - [x] Add an expand all accordion button
 - [x] Put H1,L1 ASD/range on the same plot. Use the assigned IFO colors on the plots
 - [x] plot p-values for sigma values on cumulative rate vs. stat plot
 - [x] Include mini followup of loudest event; loudest events should be in the dropdown tab for result tab

last example version
https://sugar-jobs.phy.syr.edu/~ahnitz/projects/paper/testing/w1/w1_test3/html/

**Comment by spxiwh** [comment]
The meta-information (sections 1 and 2 of the old-style ihope pages) should be available in the new page. I can look at porting this over to the new interface.

**Comment by ahnitz** [comment]
Ian,

Ok, great. Chris, has an example of some segment information on his daily page, though not a full replacement for section two. There is automatic rendering of segment xml files into this format. 

https://ldas-jobs.ligo-wa.caltech.edu/~cbc/daily_cbc_offline/bns_gds/201506/20150614/segments/

**Comment by cmbiwer** [comment]
#134 adds a sitemap.

**Comment by cmbiwer** [comment]
More tasks to add to list:
 - [ ] Units on all plots
 - [ ] segment and veto information plots
 - [ ] Use green for L1 and red for H1 on all plots
 - [ ] Add a overflow bin for extreme outliers on histograms
 - [ ] Fix x-axis limit on histograms
 - [ ] Change "without little dogs" label in legend to "closed-box background"; explain in caption
 - [ ] Define injected decisive distance in caption
 - [ ] Show linear and log scale for found/missed plot
 - [ ] is there any template bank information we can show on the summary page?
 - [ ] Show summary page at a commissioner meeting/telecon
 - [ ] Caption explanation that walks a LSC user with only knowledge of Sensemon range through how it relates to the sensitive distance plots
 - [ ] Add 1.4-1.4 line to sensitive distance plot on summary page
 - [ ] Figure out the scaling factor between L1 and H1 for how SNRs are relative, since they are not collocated
 - [ ] Add an expand all accordion button

**Comment by cmbiwer** [comment]
PR #137 adds the expand/collapse all button so I've checked it off.

**Comment by spxiwh** [comment]
It is nice that pycbc_page_sensitivity now has a sig-type option. However I think it would be *really* useful to be able to plot sensitivity vs SNR. Assuming that we actually recover signals, this would give us a sense of what we *should* acheive in terms of sensitivity.

..... In general, we need some way of looking at the sensitivity plot and comparing against what the sensitivity *should* be.

**Comment by ahnitz** [comment]
Ian,

You want to plot against the raw SNR and *NOT* NewSNR? (which is the
current option)

**Comment by ahnitz** [comment]
Would another good measure of this be the sensitivity as a function of
decisive injected distance?

**Comment by ahnitz** [comment]
Nvm, I'm not sure what I was thinking there. I don't think my last
suggestion makes sense.

**Comment by spxiwh** [comment]
Hi Alex,

Yes, I would like the option to plot against *raw* SNR.

Cheers
Ian

**Comment by spxiwh** [comment]
Like this:

https://ldas-jobs.ligo.caltech.edu/~kent/GSTLAL/OffLine/BBH/EngRun7/FullRun/1117400416-1118330880-Fri_3_Jul_2015-VetoDefII/Images/H1L1-GSTLAL_INSPIRAL_PLOT_SENSITIVITY_ALL_LLOID_COMBINED_RANGE_VS_SNR_BINNED_BY_TOTAL_MASS-1117400416-930448.png

**Comment by cmbiwer** [comment]
Here's another list of things to do:
  [ ] Time range of search should be shown (ie. GPS start and GPS end times)
  [ ] Rank found injections by IFAR
  [ ] Plot sensitive chirp distance vs IFAR
  [ ] Plot how much time was removed from the actual coincident analysis
  [ ] In the single plot explain how vetoes are applied
  [ ] Color bars on hexplot broken
  [ ] Command lines and caption need to be to set for hexplots

**Comment by cmbiwer** [comment]
I just got some more feedback on the pages. Here's some things to consider:

 - [ ] Can we toggle between GPS time and UTC time? Detchar tends to work in UTC but our pages are in GPS
 - [ ] Can we fix the y-axis of the single-detector histograms? It would be useful perhaps comparing different runs for each week of O1
 - [ ] Can we display on the axis label the name of the ranking statistic? The label Ranking statistic isn't very informative

**Comment by tdent** [comment]
Couple more points I noticed: 
 - [ ] On the sensitivity plots, the titles of (sub)sections are not different for the sensitive distance and the volume-times-time, both are labelled as 'Sensitive Distance' so you can't tell which is which.  I would go for 'Sensitive Volume \times Time' for the second. 
 - [ ] Also, the volume x time plot will be a lot more legible (i.e. content easier to evaluate) if the y-axis is made logarithmic, eg https://sugar-jobs.phy.syr.edu/~ahnitz/projects/bigdog_rerun/test/a2/gw/html/6._search_sensitivity/H1L1-PLOT_SENSITIVITY_ALL_MCHIRPVT_ALLINJ-967593543-1209744.png 
the numerical values and dependence of the lower 2 bins are essentially invisible with the linear axis.

**Comment by tdent** [comment]
- [ ] In the found/missed decisive distance vs. time plot, the missed injections should, by default, be plotted on top.  Currently they are not, eg https://sugar-jobs.phy.syr.edu/~ahnitz/projects/bigdog_rerun/test/a2/gw/html/5._injections/5.1_1INJ/H1L1-PLOT_FOUNDMISSED_MCHIRP_STATIC_GRADM_1INJ-967593543-1209744.png .  The reason for putting missed inj on top is to diagnose if there are specific times with closeby missed injections indicating crappy data.  (You won't see times like that in S6D analysis because these times were already vetoed by Andy :weary:)

**Comment by duncan-brown** [comment]
Notes from Ian

- [ ] Color coding ifo on A1
- [ ] Put full list of various segment times somewhere
- [ ] Caption of A3 is unclear
- [ ] remove jargon from all of section A
- [ ] Add line on A4 to represent bank generation PSD (if fixed bank).
- [ ] A5 in days/UTC?
- [ ] Better presentation of A5
- [ ] Is the legend in A5 a problem?
- [ ] A5 caption is not very good.
- [ ] A5 inspiral range vs mass is missing.
- [ ] Tom would like to show the full range of SNR on A6/8, Tom proposes log SNR
